# Generated by Django 4.1.1 on 2022-10-18 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyer', '0002_group_students_student_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storyer.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storyer.group'),
        ),
    ]
