# Generated by Django 4.1.1 on 2022-10-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyer', '0003_alter_group_name_alter_group_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='students',
        ),
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='preferences',
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(unique=True)),
                ('date_listed', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storyer.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storyer.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='preferences',
            field=models.ManyToManyField(through='storyer.Preference', to='storyer.group'),
        ),
    ]
