# Generated by Django 4.1.1 on 2022-10-19 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyer', '0004_remove_assignment_students_remove_group_students_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='group',
            new_name='group_preference',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='storyer.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='preferences',
            field=models.ManyToManyField(through='storyer.Preference', to='storyer.student'),
        ),
    ]
