# Generated by Django 4.1.1 on 2022-10-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyer', '0008_remove_student_assigned_group_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
