# Generated by Django 4.1.1 on 2022-10-23 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyer', '0010_alter_preference_date_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='group_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyer.group'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyer.student'),
        ),
    ]
