# Generated by Django 4.1.1 on 2022-10-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyer', '0011_alter_preference_group_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storyer.group'),
        ),
    ]
